// All reusable variables here
#let myLang = "it"
#let myName = "Orlando Virgilio Maria Ferazzani"
#let myMatricola = "2058653"
#let myTitle = "WebApp per attività laboratoriali di OpenDay"
#let myDegree = "Tesi di laurea"
#let myUni = "Università degli Studi di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof.ssa "
#let myProf = "Prof.ssa Ombretta Gaggi"
#let myCompany = "Dipartimento di Matematica"
#let myTutor = "Prof. Claudio Palazzi"
#let myLocation = "Padova"
#let myAA = "2024-2025"
#let myTime = "Luglio 2025"
