name: Compile Typst documents
on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: checkout the builds repo
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
          token: ${{secrets.ORLI_TOKEN}}
      - name: move master to runner.temp
        run: |
          mv master "${RUNNER_TEMP}"
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - name: typst compile
        run: |
          typst compile thesis.typ Orlando_Ferazzani.pdf;
      - name: push to builds repo
        run: |
          pushd "${RUNNER_TEMP}/master"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "$(date)" || continue
          git push
        env:
          TZ: Europe/Rome
