name: Compile Typst documents
on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: checkout the builds repo
        uses: actions/checkout@v4
        with:
          ref: master
          path: master
          token: ${{secrets.ORLI_TOKEN}}

      - name: move master to runner.temp
        run: |
          mv master "${RUNNER_TEMP}"

      - name: install typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz -o typst.tar.xz
          tar -xf typst.tar.xz
          TYPST_DIR=$(find . -type d -name "typst-*")
          sudo mv "$TYPST_DIR/typst" /usr/local/bin/typst
          typst --version

      - name: typst compile
        run: |
          typst compile thesis.typ Orlando_Ferazzani.pdf

      - name: copy compiled PDF to build repo
        run: |
          cp Orlando_Ferazzani.pdf "${RUNNER_TEMP}/master/"

      - name: push to builds repo
        run: |
          pushd "${RUNNER_TEMP}/master"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "$(date)" || true
          git push
        env:
          TZ: Europe/Rome
